export interface ChecklistItem {
  id: string;
  label: string;
}

export interface ChecklistCategory {
  id: string;
  title: string;
  description: string;
  icon: string;
  items: ChecklistItem[];
}

function make(prefix: string, labels: string[]): ChecklistItem[] {
  return labels.map((label, i) => ({ id: `${prefix}-${i}`, label }));
}

export const CHECKLIST_CATEGORIES: ChecklistCategory[] = [
  {
    id: "bundles",
    title: "Central Comunitária",
    description: "Pacotes de cada sala",
    icon: "landmark",
    items: make("bundles", [
      "Pacote de Forragem da Primavera",
      "Pacote de Forragem do Verão",
      "Pacote de Forragem do Outono",
      "Pacote de Forragem Exótica",
      "Pacote de Construção",
      "Pacote de Plantações da Primavera",
      "Pacote de Plantações do Verão",
      "Pacote de Plantações do Outono",
      "Pacote de Qualidade",
      "Pacote Animal",
      "Pacote do Artesão",
      "Pacote de Peixes de Rio",
      "Pacote de Peixes de Lago",
      "Pacote de Peixes do Oceano",
      "Pacote de Pesca Noturna",
      "Pacote de Peixes Especiais",
      "Pacote de Armadilhas para Caranguejo",
      "Pacote do Ferreiro",
      "Pacote do Geólogo",
      "Pacote do Aventureiro",
      "Pacote do Chef",
      "Pacote de Pesquisa de Campo",
      "Pacote de Ração",
      "Pacote do Encantador",
      "Cofre: doar 2.000g",
      "Cofre: doar 5.000g",
      "Cofre: doar 10.000g",
      "Cofre: doar 25.000g",
      "Restaurar a Estufa",
      "Restaurar a Ponte da Praia",
      "Restaurar a Linha de Trem",
    ]),
  },
  {
    id: "skills",
    title: "Habilidades",
    description: "Alcançar o nível 10 em cada habilidade",
    icon: "sprout",
    items: make("skills", [
      "Agricultura nível 10",
      "Mineração nível 10",
      "Forragem nível 10",
      "Pesca nível 10",
      "Combate nível 10",
    ]),
  },
  {
    id: "tools",
    title: "Ferramentas",
    description: "Melhorar todas as ferramentas",
    icon: "hammer",
    items: make("tools", [
      "Enxada de Irídio",
      "Regador de Irídio",
      "Machado de Irídio",
      "Picareta de Irídio",
      "Lata de Lixo de Irídio",
      "Foice Dourada",
    ]),
  },
  {
    id: "buildings",
    title: "Edifícios da Fazenda",
    description: "Construir e melhorar a fazenda",
    icon: "warehouse",
    items: make("buildings", [
      "Silo",
      "Celeiro Grande",
      "Celeiro Deluxe",
      "Galinheiro Grande",
      "Galinheiro Deluxe",
      "Poço",
      "Estábulo",
      "Galpão",
      "Galpão Grande",
      "Tanque de Peixes",
      "Casa do Slime",
      "Celeiro Subterrâneo",
      "Casa nível 1 (quarto extra)",
      "Casa nível 2 (andar de cima)",
      "Casa nível 3 (berçário)",
      "Estúdio de Terrarium (dinheiro de ouro)",
    ]),
  },
  {
    id: "mining",
    title: "Mineração e Combate",
    description: "Cavernas, masmorra do crânio e monstros",
    icon: "pickaxe",
    items: make("mining", [
      "Chegar ao andar 40 das Minas",
      "Chegar ao andar 80 das Minas",
      "Chegar ao andar 120 das Minas",
      "Chegar ao andar 100 da Caverna do Crânio",
      "Conseguir uma Estreladrop na Caverna do Crânio",
      "Erradicar Slimes (Lenhador)",
      "Erradicar Morcegos (Espeleólogo)",
      "Erradicar Caranguejos-de-Pedra (Colecionador de Pequenas Rochas)",
      "Erradicar Insetos de Caverna (Exterminador de Insetos)",
      "Erradicar Duggies (Detetive de Buracos)",
      "Erradicar Esqueletos (Osteologista)",
      "Erradicar Espíritos do Vazio (Caçador de Fantasmas)",
      "Erradicar Sprites de Magma (Extintor de Chamas)",
      "Encontrar uma espada galáctica ou machado galáctico",
    ]),
  },
  {
    id: "crops",
    title: "Cultivo",
    description: "Plantar cada cultivo pelo menos uma vez",
    icon: "wheat",
    items: make("crops", [
      "Batata",
      "Couve",
      "Feijão-verde",
      "Alho-poró",
      "Rabanete",
      "Ruibarbo",
      "Cevada",
      "Cenoura",
      "Cauliflower (Couve-flor)",
      "Tulipa",
      "Kale",
      "Framboesa",
      "Melancia",
      "Milho",
      "Girassol",
      "Tomate",
      "Pimenta",
      "Amora",
      "Amaranto",
      "Beterraba",
      "Repolho",
      "Melão",
      "Mirtilo",
      "Abóbora",
      "Uva",
      "Berinjela",
      "Trigo",
      "Soja",
      "Feno artesanal",
      "Cranberry",
      "Feijão-fava",
      "Cana-de-açúcar",
      "Café",
      "Alho",
      "Espinafre",
      "Morango (evento da Rainha das Flores)",
      "Cactus fruit",
      "Ancient Fruit (Fruta Antiga)",
      "Cogumelo Roxo",
      "Sweet Gem Berry (Baga Gema Doce)",
    ]),
  },
  {
    id: "foraging",
    title: "Forragem",
    description: "Coletar todos os itens de forragem",
    icon: "leaf",
    items: make("foraging", [
      "Samambaia-avestruz",
      "Cebolinha selvagem",
      "Dente-de-leão",
      "Morango silvestre",
      "Casca de bordo",
      "Trufa",
      "Gengibre selvagem",
      "Cogumelo comum",
      "Framboesa selvagem",
      "Amoreira selvagem",
      "Espinheiro",
      "Vinho de sabugueiro (elderberry)",
      "Cogumelo âmbar",
      "Casca de nogueira",
      "Rebento de bordo",
      "Cristal de gelo",
      "Groselha",
      "Feto-cristal",
      "Cogumelo vermelho",
      "Casca de carvalho",
      "Castanha",
      "Caqui",
      "Raiz de bordo",
      "Batata roxa selvagem",
      "Semente de girassol",
      "Coral",
      "Ouriço-do-mar",
      "Alga marinha",
      "Alga vermelha",
      "Nautilus",
      "Concha espiralada",
      "Trevo de quatro folhas",
      "Cogumelo mágico",
      "Rizoma de lótus branco",
    ]),
  },
  {
    id: "fishing",
    title: "Pesca",
    description: "Pescar cada espécie de peixe",
    icon: "fish",
    items: make("fishing", [
      "Peixe-anchova",
      "Enguia",
      "Sardinha",
      "Robalo",
      "Linguado",
      "Salmão",
      "Bagre",
      "Carpa",
      "Truta arco-íris",
      "Truta marrom",
      "Salmonete",
      "Perca",
      "Caranguejo-azul",
      "Lagosta",
      "Camarão",
      "Mexilhão",
      "Ostra",
      "Caranguejo-ferradura",
      "Baiacu",
      "Peixe-espada",
      "Tubarão",
      "Atum",
      "Peixe-borboleta",
      "Cavala",
      "Alabote",
      "Enguia-elétrica",
      "Peixe-lua",
      "Sturgeon (Esturjão)",
      "Super Cavala",
      "Woodskip",
      "Pupfish",
      "Stonefish",
      "Ice Pip",
      "Lava Eel",
      "Cave Jelly",
      "River Jelly",
      "Sea Jelly",
      "Midnight Carp",
      "Midnight Squid",
      "Squid",
      "Octopus",
      "Peixe fantasma",
      "Slimejack",
      "Peixe-espada de gelo",
      "Void Salmon",
      "Scorpion Carp",
      "Legend (Peixe Legenda)",
      "Crimsonfish",
      "Angler",
      "Glacierfish",
      "Mutant Carp",
      "Peixe de barril de lixo",
    ]),
  },
  {
    id: "cooking",
    title: "Culinária",
    description: "Cozinhar cada receita",
    icon: "chef-hat",
    items: make("cooking", [
      "Salada",
      "Omelete",
      "Coalhada de feijão-frito",
      "Sashimi de carpa",
      "Torta de mirtilo",
      "Pizza",
      "Bagel",
      "Tarte de morango",
      "Suco de mirtilo",
      "Ensopado de peixe",
      "Sopa de pão de milho",
      "Pão de banana",
      "Sopa de cogumelos",
      "Pão de trufa",
      "Chowder de mexilhões",
      "Bisque de lagosta",
      "Nachos de caranguejo",
      "Salada picante",
      "Salada de macarrão",
      "Pizza de couve",
      "Fritada de arroz",
      "Torta de abóbora",
      "Radish Salad (Salada de rabanete)",
      "Fried Egg (Ovo frito)",
      "Espaguete",
      "Fried Calamari (Lula frita)",
      "Torta de morango",
      "Tarte de framboesa",
      "Vegetable Medley",
      "Complete Breakfast",
      "Fiddlehead Risotto",
      "Poppyseed Muffin",
      "Chocolate Cake",
      "Pink Cake",
      "Rhubarb Pie",
      "Cookie",
      "Farmer's Lunch",
      "Survival Burger",
      "Dish O' The Sea",
      "Miner's Treat",
      "Roots Platter",
    ]),
  },
  {
    id: "crafting",
    title: "Artesanato",
    description: "Aprender cada receita de fabricação",
    icon: "hammer",
    items: make("crafting", [
      "Furnace (Forno)",
      "Scarecrow (Espantalho)",
      "Sprinkler (Aspersor)",
      "Sprinkler de qualidade",
      "Sprinkler de irídio",
      "Cheese Press",
      "Loom (Tear)",
      "Keg (Barril)",
      "Preserves Jar (Pote de conserva)",
      "Oil Maker",
      "Mayonnaise Machine",
      "Bee House",
      "Recycling Machine",
      "Charcoal Kiln",
      "Crystalarium",
      "Seed Maker",
      "Bomb (Bomba)",
      "Mega Bomb",
      "Sturdy Ring",
      "Warp Totem: Farm",
      "Warp Totem: Mountains",
      "Warp Totem: Beach",
      "Rain Totem",
      "Torch (Antorcha)",
      "Campfire",
      "Wood Fence / Stone Fence / Iron Fence / Hardwood Fence",
      "Gate (Portão)",
      "Chest (Baú)",
      "Scarecrow de Rainha das Fadas",
      "Cask (Barril de envelhecimento)",
      "Worm Bin",
      "Tapper (Extrator de seiva)",
      "Heavy Tapper",
      "Slime Incubator",
      "Slime Egg-Press",
      "Cristal Path",
      "Wood/Stone Floor",
      "Wooden/Stone Sign",
      "Lightning Rod",
    ]),
  },
  {
    id: "museum",
    title: "Museu",
    description: "Doar coleções de artefatos e minerais",
    icon: "gem",
    items: make("museum", [
      "Completar a coleção de artefatos",
      "Completar a coleção de minerais",
      "Doar a primeira peça no museu",
    ]),
  },
  {
    id: "relationships",
    title: "Relacionamentos",
    description: "Amizade máxima com os moradores",
    icon: "heart",
    items: make("relationships", [
      "Casar-se com alguém",
      "Ter um filho",
      "Ter dois filhos",
      "Amizade máxima: Abigail",
      "Amizade máxima: Alex",
      "Amizade máxima: Elliott",
      "Amizade máxima: Emily",
      "Amizade máxima: Haley",
      "Amizade máxima: Harvey",
      "Amizade máxima: Leah",
      "Amizade máxima: Maru",
      "Amizade máxima: Penny",
      "Amizade máxima: Sam",
      "Amizade máxima: Sebastian",
      "Amizade máxima: Shane",
      "Amizade máxima: Caroline",
      "Amizade máxima: Clint",
      "Amizade máxima: Demetrius",
      "Amizade máxima: Evelyn",
      "Amizade máxima: George",
      "Amizade máxima: Gus",
      "Amizade máxima: Jodi",
      "Amizade máxima: Kent",
      "Amizade máxima: Lewis",
      "Amizade máxima: Linus",
      "Amizade máxima: Marnie",
      "Amizade máxima: Pam",
      "Amizade máxima: Pierre",
      "Amizade máxima: Robin",
      "Amizade máxima: Willy",
      "Amizade máxima: Wizard",
      "Amizade máxima: Dwarf",
      "Amizade máxima: Krobus",
      "Amizade máxima: Sandy",
    ]),
  },
  {
    id: "achievements",
    title: "Conquistas Especiais",
    description: "Metas e marcos de fim de jogo",
    icon: "trophy",
    items: make("achievements", [
      "Alcançar Perfeição na fazenda",
      "Full Shipment (enviar todos os itens)",
      "Local Legend (todas as habilidades no nível máximo)",
      "A Complete Collection (museu completo)",
      "Master Angler (todos os peixes)",
      "Protector of the Valley (todos os monstros erradicados)",
      "Full House (casar e ter dois filhos)",
      "Homesteader (ganhar 50.000g)",
      "Legend (ganhar 1.000.000g)",
      "Cliques Populares (amizade máxima com todos)",
      "Restaurar a Central Comunitária por completo",
      "Derrotar o Golem de Prismatic Shard",
      "Completar o Belo Jardim (evento especial)",
      "Obter a Espada Galáctica",
      "Obter todas as Estreladrops",
    ]),
  },
];

export const TOTAL_TASKS = CHECKLIST_CATEGORIES.reduce(
  (sum, cat) => sum + cat.items.length,
  0,
);
